# Generated by Django 3.1.2 on 2021-08-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='diseases',
            field=models.ManyToManyField(to='Patient.Diseases'),
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
