# Generated by Django 3.1.2 on 2021-08-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_doctors_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='specialization',
        ),
    ]
