# Generated by Django 3.1.2 on 2021-08-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_auto_20210804_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='fees',
        ),
    ]
