# Generated by Django 3.1.2 on 2021-08-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_auto_20210804_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='date',
        ),
    ]
