# Generated by Django 3.1.2 on 2021-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0010_remove_patients_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
