# Generated by Django 3.1.2 on 2021-08-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0012_auto_20210804_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
