# Generated by Django 3.1.2 on 2021-08-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0014_auto_20210804_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='today',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
