# Generated by Django 3.1.2 on 2021-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0015_auto_20210804_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='date',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='today',
        ),
        migrations.AddField(
            model_name='patients',
            name='from_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='till_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
