# Generated by Django 3.1.2 on 2021-08-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0016_auto_20210804_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='till_date',
        ),
        migrations.AddField(
            model_name='patients',
            name='date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='timeslot',
            field=models.IntegerField(blank=True, choices=[(0, '09:00 – 09:30'), (1, '10:00 – 10:30'), (2, '11:00 – 11:30'), (3, '12:00 – 12:30'), (4, '13:00 – 13:30'), (5, '14:00 – 14:30'), (6, '15:00 – 15:30'), (7, '16:00 – 16:30'), (8, '17:00 – 17:30')], null=True),
        ),
    ]
